<h2 align='center'>NLP Tutorial: Text Representation - Bag Of Words (BOW)</h2>

In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

D:\Jupyter\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [5]:
df = pd.read_csv("fake_or_real_news.csv", encoding = 'unicode_escape')
df

,text,label,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138
0,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U.S. Secretary of State John F. Kerry said Mon...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"â Kaydee King (@KaydeeKing) November 9, 2016...",FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,It's primary day in New York and front-runners...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7790,The State Department told the Republican Natio...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7791,The âPâ in PBS Should Stand for âPlutocr...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7792,Anti-Trump Protesters Are Tools of the Oligar...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7793,"ADDIS ABABA, Ethiopia âPresident Obama conve...",REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7794,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.dropna(subset=['text'], inplace=True)
df.dropna(subset=['label'], inplace=True)
df

,text,label,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138
0,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U.S. Secretary of State John F. Kerry said Mon...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"â Kaydee King (@KaydeeKing) November 9, 2016...",FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,It's primary day in New York and front-runners...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7790,The State Department told the Republican Natio...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7791,The âPâ in PBS Should Stand for âPlutocr...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7792,Anti-Trump Protesters Are Tools of the Oligar...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7793,"ADDIS ABABA, Ethiopia âPresident Obama conve...",REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7794,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#df2=df.drop(df.iloc[:,2:139], axis=1)
#df2

# Keep only required columns
df2 = df[['text', 'label']]

In [9]:
#Showing label information which are not FAKE or REAL
#df_filtered = df2[~df2['label'].isin(['FAKE', 'REAL'])]
#df_filtered

# Keep only valid labels
df2 = df2[df2['label'].isin(['FAKE', 'REAL'])]

In [10]:
# Deleting rows where label is not FAKE or REAL
#df2 = df2.loc[(df2["label"]=='FAKE') | (df2["label"]=='REAL')]
df2

                                                   text label
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE
2     U.S. Secretary of State John F. Kerry said Mon...  REAL
3     â Kaydee King (@KaydeeKing) November 9, 2016...  FAKE
4     It's primary day in New York and front-runners...  REAL
...                                                 ...   ...
7790  The State Department told the Republican Natio...  REAL
7791  The âPâ in PBS Should Stand for âPlutocr...  FAKE
7792   Anti-Trump Protesters Are Tools of the Oligar...  FAKE
7793  ADDIS ABABA, Ethiopia âPresident Obama conve...  REAL
7794  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL

[6315 rows x 2 columns]

In [11]:
#df.label.value_counts()
df2.isnull().sum()

text     0
label    0
dtype: int64

In [15]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6315 entries, 0 to 7794
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    6315 non-null   object
 1   label   6315 non-null   object
dtypes: object(2)
memory usage: 148.0+ KB

In [16]:
df2.shape

(6315, 2)

In [17]:
df2

                                                   text label
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE
2     U.S. Secretary of State John F. Kerry said Mon...  REAL
3     â Kaydee King (@KaydeeKing) November 9, 2016...  FAKE
4     It's primary day in New York and front-runners...  REAL
...                                                 ...   ...
7790  The State Department told the Republican Natio...  REAL
7791  The âPâ in PBS Should Stand for âPlutocr...  FAKE
7792   Anti-Trump Protesters Are Tools of the Oligar...  FAKE
7793  ADDIS ABABA, Ethiopia âPresident Obama conve...  REAL
7794  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL

[6315 rows x 2 columns]

<h3>Train test split</h3>

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df2.text, df2.label, test_size=0.2, random_state=1)

In [19]:
X_train.shape

(5052,)

In [20]:
X_test.shape

(1263,)

In [21]:
X_test

1602    Posted on November 4, 2013 by joandarc | 12 Co...
7023    Today the White House will hold the annual Eas...
3126    \nA grim new Ministry of Defense ( MoD ) repor...
5723    The Bureau of Land Management (BLM) claims to ...
2341    The Kremlin on Friday played down the possibil...
                              ...
2423    19 mins ago 3 Views 0 Comments 0 Likes It's fa...
6212    Home | World | Brexit Lost: Scuppered By May a...
500     The federal government must make regular inter...
4852    Both Donald Trump and Hillary Clinton have str...
2642    (CNN) Sen. John McCain is chastising GOP leade...
Name: text, Length: 1263, dtype: object

In [22]:
X_train

2789    More than 50 individuals and entities have she...
4976    FBI Director may be sacked for intrusion into ...
1906    The White House made formal veto threats Wedne...
5312    Republican presidential candidate John Kasich ...
3076    The Supreme Court gutted a key portion of the ...
                              ...
1220    The battle over the budget that President Obam...
6557    Email \nWell, this isnât good. \nMost people...
4979    Chris Christie depicts Marco Rubio as a truant...
235      Why Hillary Won't Unleash WWIII By Pepe Escob...
6522    On 23 September 1952, vice presidential candid...
Name: text, Length: 5052, dtype: object

In [199]:
type(y_train)

pandas.core.series.Series

In [17]:
X_train.values

array(['Running mates? Itâ\x80\x99s not even May, and already weâ\x80\x99re talking running mates? Then let me toss Elizabeth Warrenâ\x80\x99s name into the mix.\n\nIâ\x80\x99m making several assumptions here â\x80\x94 in a year when assuming anything is dangerous. First, I believe Ted Cruzâ\x80\x99s desperate gamble of adding Carly Fiorina to his â\x80\x9cticketâ\x80\x9d will fail. He was right to throw some kind of Hail Mary, but I donâ\x80\x99t see how Fiorina attracts enough new support for Cruz to win the Indiana primary on Tuesday. And if he loses there, heâ\x80\x99s pretty much toast.\n\nDonald Trumpâ\x80\x99s landslide wins this week in the Northeast gave him a bigger haul of convention delegates than even his most optimistic boosters had expected. If momentum still counts for anything in politics, Trump has it. And if he wins Indiana â\x80\x94 polls show him with about a six-point lead â\x80\x94 his path to the Republican nomination looks wide enough to taxi the rest of the way in his BoeingÂ\xa0757.\n\nIâ\x80\x99m also assuming that Hillary Clinton will be the Democratic nominee. The delegate math is just brutal: There is simply no viable way now for Bernie Sanders to catch up. Sanders appeared to acknowledge reality this week when he announced that his campaign would lay off â\x80\x9chundredsâ\x80\x9d of paid staff members. He will use his clout at the convention, he said, to â\x80\x9cput together the strongest progressive agenda that any political party has ever seen.â\x80\x9d\n\nWhich is where Warren comes in.\n\nIt is absurd to claim that Clinton does not merit the â\x80\x9cprogressiveâ\x80\x9d label; she has the scars from decades of attacks by the â\x80\x9cvast right-wing conspiracyâ\x80\x9d to prove her bona fides. But on most issues â\x80\x94 gun control being a glaring exception â\x80\x94 Sanders is well to her left. And, as his surprising campaign has shown, thatâ\x80\x99s where the energy and excitement in the Democratic Party happen to be this year.\n\nIf there is a specific issue on which Clinton is weak with the Democratic left, it is not the FBI investigation of her emails. It is her perceived coziness with Wall Street, highlighted by the six-figure speaking fees she was paid by investment bank Goldman Sachs.\n\nSandersâ\x80\x99s central theme is that the rich and powerful have distorted our political and economic systems to favor their own selfish interests. He blasts Clinton not only for the Goldman speeches but also for mining Wall Street for campaign cash. My assumption is that Sanders, should he fall short of the nomination, will give Clinton his full-throated support. But will his most ardent supporters follow?\n\nAs Clintonâ\x80\x99s running mate, Warren could erase this potential weakness with the Democratic base. She has spent her Senate career becoming known as the scourge of Wall Street. No political figure is more closely identified with efforts to curb the excesses of the financial system.\n\nWarren would also help address another potential vulnerability. If the general-election matchup is Trump vs. Clinton â\x80\x94 and that seems increasingly likely â\x80\x94 it is becoming clear that on the question of U.S. military involvement around the world, Trump will position himself to the left of Clinton.\n\nThe foreign policy speech that Trump delivered Wednesday was, for the most part, vague and anodyne. His overarching theme is â\x80\x9cAmerica first,â\x80\x9d he said. To the extent the phrase means anything, it seems to promise that a President Trump would be extremely reluctant to deploy U.S. combat forces in any sort of â\x80\x9cworldâ\x80\x99s policemanâ\x80\x9d role. Trump has even questioned the viability of NATO in its present form.\n\nClinton is a foreign policy traditionalist. As secretary of state, she was more hawkish than President Obama â\x80\x94 she pushed for more vigorous intervention in Syria, for example. She has long since apologized for her vote to authorize the Iraq War, but Sanders continues to attack her for it. Trump would surely do the same.\n\nWarren wasnâ\x80\x99t in Congress when the Iraq War began, and national security isnâ\x80\x99t the issue with which she is identified. But her views fit squarely with those of the partyâ\x80\x99s progressive wing.\n\nWarren also has a compelling personal story of having risen from modest beginnings to become a Harvard professor and then a U.S. senator. The fact that she and Clinton would be the first all-female major party ticket should be irrelevant, but isnâ\x80\x99t. To many voters, it would be thrilling.\n\nI can think of several other potential running mates for Clinton. Funny, but I draw a blank when trying to come up with a suitable partner for Trump. Maybe heâ\x80\x99ll just go it alone.\n\nRead more from Eugene Robinsonâ\x80\x99s archive, follow him on Twitter or subscribe to his updates on Facebook. You can also join him Tuesdays at 1 p.m. for a live Q&A.',
       'Colorado Springs, Colorado (CNN) Ted Cruz on Saturday clinched the support of every pledged delegate in Colorado, capturing all of the final 13 delegates who will go to the national convention in July and demonstrating his organizational strength in the all-important delegate race.\n\nEven though voters didn\'t head to the polls Saturday, Cruz\'s strength here could help deny Donald Trump the 1,237 delegates that he needs to clinch the nomination.\n\nCruz\'s victory Saturday, combined with delegates he had already earned, hands him 30 of the 37 delegates across the state who are legally bound to support him on the first ballot at the convention, along with four other delegates who gave him verbal commitments of support.\n\n"Today was another resounding victory for conservatives, Republicans, and Americans who care about the future of our country," the Cruz campaign said a statement. "Utah, North Dakota, Wisconsin, and tonight\'s incredible results in Colorado have proven this: Republicans are uniting behind our campaign because they want a leader with real solutions who will bring back jobs, freedom, and security."\n\nEarlier in the afternoon, Cruz had urged state Republicans here at the Broadmoor Arena to help him defeat Trump.\n\n"If we continue to stand united, we are going to win this Republican nomination. We are going to win the general election. We are going to win the state of Colorado and we are going to turn this country around," Cruz said to huge cheers from the arena floor.\n\nIn yet another sign of his airtight ground game, Cruz spoke before a huge screen displaying his slate of delegates for the final 13 spots, and he noted that his slate was also printed on the bright orange T-shirts that his many volunteers were wearing on the state convention floor.\n\nTrump\'s campaign, by contrast, initially distributed fliers listing the campaign\'s national delegate candidates that were riddled with errors. The flier displaying the Trump slate is supposed to be the tip sheet that party members use to fill out their ballot. But on the first slate that the Trump campaign was giving out, more than a half dozen of their delegate candidates were listed with the wrong delegate number. At least one of the delegate numbers corresponded to a delegate supporting Cruz.\n\nThe Trump campaign reprinted the flier, but the second flier also included several errors.\n\nBefore the voting began, Trump campaign adviser Patrick Davis said in an interview that the team had been given "incomplete" information by the Colorado Republican Party about delegate numbers.\n\nLater in the evening, as the votes were being counted, senior Trump adviser Alan Cobb said several supporters had told the campaign that their ballot number had changed numerous times or that their name did not appear on the party\'s official list of national delegate candidates even though they had filled out the proper paperwork.\n\nAlan Cobb, the senior adviser to Trump, said the campaign was looking into the reports of balloting problems and was not ruling out a challenge to seating the Colorado delegation at the national convention in July.\n\nA spokesman for the state party said it was looking into the reports but had no immediate comment.\n\nIt was unclear how much confusion that caused, but the Trump campaign has acknowledged that it did not expect to win any delegates in Colorado.\n\nWhile there was fervent enthusiasm for Cruz, former New Hampshire Sen. John E. Sununu, who was Ohio Gov. John Kasich\'s surrogate at the gathering, was greeted with polite applause.\n\n"We\'ve got to unify behind that candidate who will win," Sununu told the crowd, pointing to Kasich\'s strength in general election polling matchups with Hillary Clinton. Kasich, however, had not won any delegates as of Saturday afternoon.\n\nTrump campaign surrogate Stephen Miller, a policy adviser to the real estate magnate, drew a warmer response by opening his speech with a focus on the issue that helped carry Trump to the top of the Republican field: Immigration.\n\n"Do you think the United States of America needs to secure its border?" Miller asked the crowd, which shouted "Yes" in response. Before even mentioning Trump\'s candidacy, Miller went on to read letters from parents who he said had lost their children to "illegal immigrant violence."\n\n"These Americans deserve a voice and I am going to give it to them today," Miller said. "It\'s the powerless who are standing up behind Mr. Trump."\n\nCruz dominated the intricate delegate selection process of the Colorado Republican Party, and in this pivotal swing state, a strong campaign organization has often made the difference between defeat and victory in the race to the White House.\n\nIn this first round for the GOP, Team Cruz once again proved its mettle -- far outpacing the efforts of Trump and Kasich in the scramble for delegates at each of the congressional district gatherings this week.\n\nBy late Friday, Cruz had swept all the available delegates in the state\'s seven congressional districts.\n\nIn the final rounds of a messy and chaotic process Friday, candidates vying to be one of Colorado\'s delegates lined up along the walls of the ballroom at a Doubletree hotel here waiting their turn to deliver campaign speeches. "You have 10 seconds. Go!" a party official barked as the first candidate stepped to the microphone Friday morning.\n\nCruz volunteers seemed to be everywhere, working the hallways where party members were crammed shoulder to shoulder among vendors peddling Cruz infinity scarves and Trump-style "Make America Great Again" hats. In one corner, a hot pink handwritten sign lured the undecided over to talk to "Cruz Persuasion Teams."\n\nThe ballroom floor was littered Cruz campaign slates (the tip sheets indicating which delegates are endorsed by the campaign). Scattered across the room were glossy copies of the "Donald Trump Voter Guide," which is actually an anti-Trump pamphlet distributed by one of the super PACs that is trying to defeat him.\n\nAmid all the jostling, shouting and chaos throughout the day Friday, delegates aligned with Cruz won again and again.\n\nTrump still maintains a wide lead over Cruz in the delegate count as the two candidates attempt to win the 1,237 delegates needed to clinch the Republican nomination.\n\nBut at a time when a contested convention looks increasingly likely, there was palpable disdain for Trump\'s candidacy among the GOP faithful here. His string of unforced errors, nasty tweets and controversial policy statements in recent weeks have clearly taken a toll.\n\n"The momentum against Trump at the activist level is just frothing," said Josh Penry, a former state senator who was Marco Rubio\'s state chairman in Colorado. "There was a time when Trump could have competed in Colorado. That time has long since passed. ... Among the activists, the tide has turned against him dramatically."\n\nTrump canceled a planned rally in Colorado this week as he focused his efforts on New York, which holds its critical primary on April 19.\n\nWhile Trump had some fervent supporters here at the state convention, it was clear from the speeches delivered by delegate candidates that his appeal has worn thin for many Republicans -- a testament to how much work the real estate magnate would have to do to unite the party if he becomes the nominee.\n\nAt Thursday night\'s gathering for Colorado\'s 7th Congressional District, 19-year-old student Angel Merlos urged the crowd to elect him as a Cruz delegate to the convention, because he said the nation\'s values and morals were at stake if Trump were to become the Republican nominee.\n\n"Morality is about how you act, how you speak, and how you carry yourself," Merlos said in interview after his brief speech in Arvada. "I believe Trump has no morals because he lies about many things. ... He contradicts himself on everything."\n\n"He thinks he knows what will help the immigration problem, but he doesn\'t," Merlos continued. "He talks about a wall -- that may do something. I don\'t know exactly what it will do. But he uses immigrants to help him build his buildings, and yet he\'s so cruel and harsh" when he talks about them, Merlos said.\n\nDelegate candidate David Head ran as an "unpledged" delegate in the hope of serving as a voice against Trump on the floor of Republican convention in July.\n\n"I think he would be a disaster for both the Republican Party and the country," said Head, who owns an insurance business in Westminster, Colorado, with his son.\n\n"He confuses intimidation and bluster with straight talk and honesty. I think he is anti-woman. I think he is saying whatever he thinks will sell to get him a vote, and I think he\'s playing on the fears and prejudices of a lot of people to intimidate people into voting for him."\n\nLibby Szabo, a Jefferson County Commissioner who won a slot as a Cruz delegate to the national convention, said as a conservative, she was troubled by Trump\'s recent comments about punishing women who have illegal abortions. (Trump backed off that position after an uproar from opposite sides of the political spectrum.)\n\n"I like that he has started a dialogue in our party that we need to have. I just don\'t see him as being consistent," Szabo said. "One week he says one thing, the next week he says another thing."\n\nTrump campaign looks to step up operation\n\nBeyond the simmering anti-Trump sentiment here, Cruz\'s strength in the delegate chase in Colorado (as well as states like North Dakota, Louisiana and Tennessee) has once again exposed the deficiencies of Trump\'s organizing operation, which is scrambling to catch up.\n\nTrump\'s allies insist there is still time to streamline their delegate wrangling operation and time to persuade even those who are resistant to his brand of politics at this moment.\n\nOne Trump adviser said they entered the Colorado GOP contests with the expectation of winning "zero delegates" -- and were pleased at the end of the day Friday that they had won two alternate delegates pledged to Trump in Congressional District 4.\n\n"This is just the beginning of a four-month process to convince the unpledged delegates and alternates in Colorado that Donald Trump means what he says, he\'s going to make America great again," said Davis, a Colorado-based political consultant who joined the Trump team this week after Trump\'s campaign manager fired their Colorado state director.\n\nIn conversations with Cruz supporters, Davis brushed off questions about Trump\'s poor standing in general election match-ups with Hillary Clinton, arguing that "polls taken today, six months away from November, are garbage, and will not be predictive on election day."\n\nAs for Cruz\'s clear organizational advantage, Davis said Trump\'s team remains undaunted.\n\n"This is an insider\'s game," Davis said, as he waited for the final votes of the day to be tabulated. "Nowhere in America, including Colorado, are insiders the heart and soul of the Trump campaign."\n\nBut the question is whether Trump can get geared up in time to win that insider\'s game.\n\nHis campaign announced an expanded role this week for veteran GOP operative Paul Manafort, who is managing convention activities for Trump -- just as he did for the presidential campaigns of Gerald Ford, Ronald Reagan, George H.W. Bush and Bob Dole.\n\nBecky Mizel, a Trump volunteer who was the former chair of the Pueblo County Republican Party in Colorado, said she wasn\'t discouraged by Trump\'s poor showing in the state.\n\n"Cruz has a very strong organization here," she said when asked about the obstacles her candidate had faced. One of Cruz\'s most powerful allies, she noted, was the Rocky Mountain Gun Owners, which circulated ubiquitous blue fliers touting Cruz delegates at every voting location this week.\n\nMizel credited the head of the group, Dudley Brown (who she counts as a friend), with "organizing the Cruz machine with the legislators who have decided to go and block Mr. Trump."\n\n"The average person on the street is working or raising their kids -- they aren\'t political junkies like the caucus attendees are -- and those are the people that are attracted to Mr. Trump," she said.\n\nAt the same time, Mizel said she was relieved that the Trump campaign now seems to grasp the gravity of the task before them as they prepare for the possibility of a contested convention.',

In [23]:
X_train.values.shape

(5052,)

In [25]:
type(X_train.values)

numpy.ndarray

<h3>Create bag of words representation using CountVectorizer</h3>

In [26]:
# from sklearn.feature_extraction.text import CountVectorizer

# v = CountVectorizer()

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words='english',
    max_df=0.7
)

X_train_tfidf = tfidf.fit_transform(X_train.values.astype('U'))

In [27]:
statements = [
            'Google has started providing unlimited cloud storage for its users',
            'Joe Biden is the US President'
         ]

statements_cv = tfidf.fit_transform(statements)
statements_cv

<2x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [28]:
statements_cv.toarray()

array([[0.        , 0.37796447, 0.37796447, 0.        , 0.        ,
        0.37796447, 0.37796447, 0.37796447, 0.37796447, 0.37796447],
       [0.57735027, 0.        , 0.        , 0.57735027, 0.57735027,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [30]:
tfidf.get_feature_names_out()

array(['biden', 'cloud', 'google', 'joe', 'president', 'providing',
       'started', 'storage', 'unlimited', 'users'], dtype=object)

In [32]:
pd.DataFrame(statements_cv.toarray(), columns=tfidf.get_feature_names_out())

,biden,cloud,google,joe,president,providing,started,storage,unlimited,users
0,0.00000,0.377964,0.377964,0.00000,0.00000,0.377964,0.377964,0.377964,0.377964,0.377964
1,0.57735,0.000000,0.000000,0.57735,0.57735,0.000000,0.000000,0.000000,0.000000,0.000000

In [38]:
tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train.values.astype('U'))
X_train_tfidf

<5052x67644 sparse matrix of type '<class 'numpy.float64'>'
	with 1724538 stored elements in Compressed Sparse Row format>

In [39]:
X_train_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [40]:
X_train_tfidf.shape

(5052, 67644)

In [41]:
X_train_tfidf[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [42]:
tfidf.get_feature_names_out()

array(['00', '000', '0000', ..., 'ðºð', 'ð¾ðºñ', 'ø¹ø'], dtype=object)

In [43]:
pd.DataFrame(X_train_tfidf.toarray(), columns=tfidf.get_feature_names_out())

,00,000,0000,000000031,00000031,000035,00006,0001pt,0002,000ft,...,î²,îµî,îµî¼î²ï,î½î¹îºî,ð²ð½ð,ð³,ð¹,ðºð,ð¾ðºñ,ø¹ø
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5047,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5048,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5050,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5051,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
tfidf.vocabulary_

{'more': 40035,
 'than': 60270,
 '50': 1414,
 'individuals': 30876,
 'and': 4253,
 'entities': 21092,
 'have': 27974,
 'shelled': 54684,
 'out': 43522,
 'at': 5716,
 'least': 35249,
 '1â': 727,
 'million': 39115,
 'apiece': 4719,
 'to': 60982,
 'big': 7901,
 'money': 39848,
 'groups': 26939,
 'backing': 6388,
 'presidential': 47246,
 'candidates': 10463,
 'with': 66395,
 'close': 12607,
 'half': 27450,
 'of': 42753,
 'the': 60299,
 'donors': 18992,
 'giving': 25990,
 'super': 58624,
 'pac': 43994,
 'aligned': 3688,
 'former': 24377,
 'florida': 23965,
 'governor': 26466,
 'jeb': 32681,
 'bush': 9993,
 '15': 320,
 'months': 39957,
 'go': 26187,
 'before': 7327,
 'election': 20292,
 'day': 16146,
 'already': 3856,
 'contributed': 14237,
 '272': 989,
 '5â': 1575,
 'independent': 30791,
 'supporting': 58742,
 'large': 34891,
 'republican': 50802,
 'field': 23384,
 'four': 24484,
 'times': 60854,
 '67â': 1658,
 'raised': 48991,
 'through': 60651,
 'their': 60343,
 'official': 42805,
 'campaigns': 10392,
 'according': 2524,
 'tally': 59485,
 'by': 10112,
 'washington': 65426,
 'post': 46765,
 'in': 30533,
 'all': 3720,
 '58': 1524,
 'dollar': 18882,
 'together': 61026,
 'were': 65793,
 'responsible': 51048,
 'for': 24213,
 '120â': 231,
 'donated': 18950,
 'gop': 26376,
 'democratic': 16902,
 'pacs': 44034,
 'june': 33242,
 '30': 1063,
 '40': 1251,
 'percent': 45113,
 'total': 61241,
 'amount': 4116,
 'those': 60572,
 'never': 41494,
 'has': 27868,
 'so': 56174,
 'much': 40386,
 'been': 7306,
 'such': 58415,
 'small': 55917,
 'number': 42340,
 'people': 45086,
 'early': 19816,
 'massive': 37816,
 'sums': 58578,
 'empowered': 20701,
 'outside': 43644,
 'that': 60287,
 'face': 22486,
 'no': 41847,
 'contribution': 14240,
 'limits': 35892,
 'are': 5066,
 'now': 42223,
 'serving': 54283,
 'as': 5388,
 'de': 16193,
 'facto': 22543,
 'arms': 5209,
 'many': 37434,
 'how': 29462,
 'backers': 6374,
 'work': 66616,
 'clearly': 12451,
 'action': 2684,
 'is': 32175,
 'who': 66034,
 'can': 10418,
 'write': 66805,
 'seven': 54335,
 'digit': 17807,
 'bigger': 7907,
 'checks': 11711,
 'said': 52678,
 'henry': 28425,
 'barbour': 6799,
 'veteran': 64532,
 'fundraiser': 25025,
 'based': 6953,
 'mississippi': 39470,
 'informally': 31085,
 'advising': 3056,
 'texas': 60229,
 'rick': 51494,
 'perry': 45274,
 'his': 28828,
 'run': 52392,
 'itâ': 32362,
 'amazing': 3967,
 'but': 10041,
 'handful': 27585,
 'really': 49469,
 'material': 37865,
 'impact': 30308,
 'on': 42997,
 'race': 48822,
 'topping': 61164,
 'list': 36007,
 'mega': 38382,
 'right': 51569,
 'new': 41506,
 'york': 67200,
 'hedge': 28244,
 'fund': 25006,
 'manager': 37262,
 'robert': 51810,
 'mercer': 38604,
 '11': 178,
 'sen': 54078,
 'ted': 59856,
 'cruz': 15425,
 'tex': 60225,
 'houston': 29452,
 'private': 47475,
 'equity': 21284,
 'investor': 31973,
 'toby': 60999,
 'neugebauer': 41440,
 'gave': 25461,
 '10â': 177,
 'another': 4489,
 'kelcy': 33682,
 'warren': 65394,
 'dallas': 15866,
 'energy': 20884,
 'executive': 22018,
 'national': 41048,
 'finance': 23514,
 'chairman': 11414,
 'perryâ': 45275,
 'campaign': 10384,
 'two': 62421,
 'pro': 47504,
 'dozen': 19192,
 'made': 36894,
 'contributions': 14241,
 'hopefuls': 29260,
 'including': 30662,
 'car': 10635,
 'magnate': 36968,
 'norman': 42078,
 'braman': 9150,
 'marco': 37487,
 'rubio': 52292,
 'tech': 59820,
 'entrepreneur': 21121,
 'darwin': 16056,
 'deason': 16253,
 'wisconsin': 66361,
 'roofing': 52002,
 'billionaire': 7968,
 'diane': 17677,
 'hendricks': 28408,
 'gov': 26450,
 'scott': 53565,
 'walker': 65225,
 'while': 65933,
 'flowing': 24001,
 'allied': 3763,
 'situation': 55528,
 'reverse': 51303,
 'side': 55184,
 '80': 1841,
 'support': 58734,
 'hillary': 28706,
 'rodham': 51882,
 'clinton': 12554,
 'her': 28433,
 'rivals': 51714,
 'went': 65791,
 'directly': 17957,
 'bernie': 7688,
 'sanders': 52894,
 'vermont': 64474,
 'he': 28064,
 'does': 18825,
 'not': 42132,
 'want': 65310,
 'flanked': 23784,
 'own': 43923,
 'wealthy': 65577,
 'allies': 3764,
 'means': 38254,
 'pump': 48236,
 'tens': 60049,
 'millions': 39118,
 'into': 31826,
 'behalf': 7370,
 'eight': 20202,
 'given': 25984,
 'priorities': 47446,
 'usa': 63882,
 'one': 43009,
 'which': 65924,
 'include': 30656,
 'george': 25690,
 'soros': 56491,
 'media': 38307,
 'haim': 27396,
 'saban': 52542,
 'film': 23476,
 'director': 17960,
 'steven': 57658,
 'spielberg': 56834,
 'first': 23651,
 'time': 60838,
 'nearly': 41213,
 'every': 21767,
 'contender': 14123,
 'backed': 6372,
 'deep': 16518,
 'pocketed': 46299,
 'ally': 3806,
 'cases': 10874,
 'several': 54343,
 'longtime': 36332,
 'advisers': 3052,
 'aides': 3375,
 'white': 65982,
 'house': 29430,
 'edged': 20009,
 'closer': 12614,
 'previous': 47343,
 'dared': 16000,
 'there': 60411,
 'norm': 42067,
 'will': 66198,
 'office': 42795,
 'david': 16112,
 'donnelly': 18982,
 'president': 47245,
 'voice': 64950,
 'group': 26934,
 'advocates': 3067,
 'reducing': 49946,
 'influence': 31063,
 'politics': 46471,
 'about': 2308,
 'they': 60459,
 'get': 25766,
 'from': 24837,
 'voters': 65033,
 'iowa': 32039,
 'hampshire': 27552,
 'benchmark': 7542,
 'direct': 17945,
 'these': 60439,
 'huge': 29575,
 'spent': 56810,
 'most': 40165,
 'year': 67078,
 'headlining': 28086,
 'high': 28658,
 'fundraisers': 25026,
 'rise': 51659,
 'helping': 28370,
 'it': 32311,
 'collect': 12979,
 'record': 49778,
 '103â': 143,
 'maintaining': 37072,
 'had': 27333,
 'yet': 67139,
 'decided': 16374,
 'whether': 65919,
 'hit': 28861,
 'its': 32352,
 'expected': 22140,
 '100â': 128,
 'goal': 26192,
 'last': 34938,
 'fundraising': 25028,
 'period': 45191,
 'when': 65903,
 'cashed': 10881,
 '82': 1862,
 'totaling': 61243,
 'among': 4107,
 'them': 60351,
 'was': 65415,
 'donation': 18957,
 'shahla': 54464,
 'ansary': 4495,
 'wife': 66132,
 'iranian': 32068,
 'diplomat': 17931,
 'hushang': 29744,
 'february': 23067,
 'racing': 48837,
 'reach': 49375,
 '100': 116,
 'spiked': 56843,
 'three': 60611,
 'weeks': 65678,
 'quarter': 48608,
 '20': 728,
 'companies': 13338,
 'largest': 34899,
 'sum': 58536,
 'coming': 13183,
 'coral': 14440,
 'gables': 25151,
 'health': 28116,
 'care': 10688,
 'miguel': 39003,
 'fernandez': 23237,
 '3â': 1249,
 'told': 61049,
 'wall': 65236,
 'street': 57986,
 'journal': 33078,
 'looking': 36343,
 'any': 4659,
 'favors': 22966,
 'am': 3933,
 'sure': 58779,
 'thereâ': 60423,
 'donor': 18991,
 'wants': 65316,
 'solar': 56306,
 'power': 46873,
 'business': 10009,
 'build': 9773,
 'submarines': 58264,
 'joked': 33000,
 'paper': 44309,
 'only': 43036,
 'because': 7246,
 'think': 60497,
 'values': 64172,
 'bushâ': 10005,
 'nomination': 41918,
 'largely': 34893,
 'financed': 23515,
 'few': 23316,
 'patrons': 44760,
 'called': 10309,
 'keep': 33659,
 'promise': 47736,
 '37â': 1201,
 '95': 2008,
 'came': 10360,
 'just': 33282,
 'contributors': 14244,
 '15â': 357,
 'wilks': 66196,
 'family': 22732,
 'cisco': 12227,
 'billions': 7974,
 'designing': 17319,
 'hydraulic': 29792,
 'fracturing': 24540,
 'trucks': 62022,
 '20â': 832,
 'unintimidated': 63270,
 'women': 66518,
 'marlene': 37625,
 'ricketts': 51498,
 'td': 59764,
 'ameritrade': 4054,
 'founder': 24472,
 'joe': 32942,
 'rubioâ': 52295,
 'conservative': 13919,
 'solutions': 56360,
 'brought': 9584,
 'slightly': 55805,
 '16â': 388,
 'third': 60519,
 'patron': 44754,
 'senator': 54082,
 'lawrence': 35095,
 'ellison': 20445,
 'chief': 11849,
 'technology': 59849,
 'officer': 42798,
 'oracle': 43228,
 'laura': 35033,
 'perlmutter': 45220,
 'marvel': 37712,
 'entertainment': 21066,
 'ceo': 11308,
 'isaac': 32178,
 'besilu': 7726,
 'stables': 57202,
 'llc': 36133,
 'horse': 29336,
 'operation': 43105,
 'owned': 43924,
 'businessman': 10013,
 'benjamin': 7592,
 'leon': 35480,
 'america': 4029,
 'leads': 35184,
 'chris': 12025,
 'christie': 12045,
 '11â': 226,
 'steve': 57657,
 'cohen': 12887,
 'alexandra': 3632,
 '2â': 1061,
 'winecup': 66273,
 'gamble': 25279,
 'ranch': 49083,
 'nevada': 41491,
 'reebok': 49959,
 'paul': 44779,
 'fireman': 23625,
 'arkansas': 5164,
 'mike': 39008,
 'huckabee': 29544,
 'little': 36070,
 'rock': 51848,
 'agribusiness': 3323,
 'ronald': 51989,
 'cameron': 10370,
 '45â': 1337,
 'carly': 10747,
 'hewlett': 28571,
 'packard': 44021,
 'fiorina': 23594,
 'univision': 63327,
 'head': 28066,
 'jerrold': 32776,
 'perenchio': 45143,
 'figure': 23431,
 'flooding': 23944,
 'alarms': 3546,
 'party': 44573,
 'strategists': 57947,
 'worry': 66678,
 'moving': 40306,
 'away': 6194,
 'unaccountable': 62647,
 'you': 67211,
 'do': 18757,
 'level': 35565,
 'playing': 46113,
 'longer': 36317,
 'fred': 24648,
 'malek': 37159,
 'senior': 54104,
 'my': 40733,
 'humble': 29628,
 'opinion': 43127,
 'pollutes': 46512,
 'process': 47545,
 'since': 55410,
 'law': 35072,
 'permits': 45241,
 'everyone': 21774,
 'going': 26274,
 'until': 63654,
 'changes': 11494,
 'almost': 3820,
 'moment': 39795,
 'led': 35286,
 'candidate': 10462,
 'doesnâ': 18827,
 'need': 41241,
 'real': 49432,
 'estate': 21534,
 'impresario': 30469,
 'donald': 18941,
 'trump': 62045,
 'claims': 12304,
 'be': 7154,
 'worth': 66701,
 'billion': 7967,
 'fbi': 23004,
 'may': 37999,
 'sacked': 52575,
 'intrusion': 31884,
 'elections': 20298,
 '08': 86,
 '2016': 773,
 'james': 32538,
 'comey': 13168,
 'nearest': 41211,
 'future': 25107,
 'thoughtless': 60579,
 'step': 57609,
 'british': 9466,
 'daily': 15837,
 'mail': 37035,
 'reported': 50727,
 'reference': 50013,
 'source': 56553,
 'obama': 42472,
 'adviser': 3051,
 'valerie': 64122,
 'jarrett': 32605,
 'convinced': 14325,
 'him': 28756,
 'necessity': 41232,
 'undertake': 62996,
 'alienated': 3679,
 'both': 8942,
 'democrats': 16912,
 'republicans': 50804,
 'thus': 60718,
 'congress': 13810,
 'leaving': 35262,
 'this': 60531,
 'issue': 32293,
 'discussed': 18181,
 'possible': 46760,
 'legal': 35330,
 'political': 46447,
 'consequences': 13907,
 'decision': 16393,
 'same': 52833,
 'other': 43466,
 'sources': 56557,
 'assert': 5564,
 'himself': 28762,
 'ready': 49416,
 'resign': 50946,
 'waiting': 65180,
 'believe': 7454,
 'prejudiced': 47126,
 'reputation': 50828,
 'bureau': 9903,
 'lost': 36436,
 'weight': 65703,
 'employees': 20689,
 'reopening': 50636,
 'investigation': 31956,
 'against': 3218,
 'apparent': 4779,
 'reason': 49513,
 'further': 25077,
 'closure': 12625,
 'case': 10872,
 'without': 66416,
 'consulting': 14057,
 'experts': 22193,
 'concerned': 13561,
 'enforcement': 20897,
 'well': 65756,
 'prosecutors': 47877,
 'pravda': 46964,
 'ru': 52262,
 'formal': 24356,
 'veto': 64542,
 'threats': 60608,
 'wednesday': 65657,
 'bills': 7982,
 'would': 66711,
 'allow': 3781,
 'construction': 14030,
 'keystone': 33802,
 'xl': 66948,
 'pipelineâ': 45883,
 'change': 11487,
 'key': 33783,
 'mandate': 37288,
 'under': 62873,
 'affordable': 3148,
 'act': 2680,
 'signaling': 55256,
 'rocky': 51869,
 'start': 57386,
 '114th': 204,
 'press': 47259,
 'secretary': 53840,
 'josh': 33057,
 'earnest': 19829,
 'announced': 4437,
 'tuesday': 62204,
 'obamaâ': 42485,
 'intends': 31566,
 'bill': 7952,
 'headed': 28073,
 'desk': 17333,
 'controlled': 14253,
 'statement': 57427,
 'administration': 2902,
 'policy': 46429,
 'elaborates': 20254,
 'objection': 42521,
 'version': 64490,
 'identical': 29983,
 'introduced': 31863,
 'senate': 54080,
 'sens': 54114,
 'john': 32957,
 'hoeven': 28964,
 'manchin': 37279,
 'va': 64049,
 'conflicts': 13745,
 'longstanding': 36330,
 'branch': 9152,
 'procedures': 47536,
 'regarding': 50143,
 'authority': 6037,
 'prevents': 47338,
 'thorough': 60564,
 'consideration': 13938,
 'complex': 13435,
 'issues': 32297,
 'could': 14692,
 'bear': 7187,
 'interests': 31639,
 'serious': 54241,
 'security': 53881,
 'safety': 52643,
 'environmental': 21150,
 'ramifications': 49054,
 'reads': 49415,
 'released': 50402,
 'management': 37259,
 'budget': 9723,
 'if': 30048,
 'presented': 47221,
 'advisors': 3059,
 'recommend': 49731,
 'adds': 2818,
 'also': 3862,
 'laid': 34694,
 'down': 19136,
 'gauntlet': 25454,
 'comes': 13162,
 'latest': 34964,
 'effort': 20122,
 'chip': 11920,
 'signature': 55263,
 'currently': 15631,
 'requires': 50848,
 'employers': 20693,
 'provide': 47995,
 'insurance': 31496,
 'full': 24972,
 'workers': 66623,
 'defined': 16636,
 'anyone': 4666,
 'working': 66630,
 'hours': 29427,
 'week': 65668,
 'or': 43226,
 'save': 53122,
 'american': 4033,
 'workersâ': 66624,
 'definition': 16642,
 'employee': 20688,
 'someone': 56392,
 'reject': 50337,
 'measure': 38266,
 'significantly': 55275,
 'increase': 30724,
 'deficit': 16626,
 'reduce': 49941,
 'americans': 4041,
 'employer': 20692,
 'coverage': 14874,
 'create': 15055,
 'incentives': 30611,
 'shift': 54764,
 'part': 44510,
 'causing': 11075,
 'problem': 47525,
 'solve': 56364,
 'rather': 49254,
 'attempting': 5832,
 'once': 43001,
 'again': 3217,
 'repeal': 50668,
 'undermine': 62934,
 'careâ': 10715,
 'tried': 61843,
 'over': 43694,
 'stop': 57827,
 'fighting': 23423,
 'old': 42908,
 'battles': 7080,
 'join': 32985,
 'forwarding': 24442,
 'an': 4171,
 'agenda': 3239,
 'focused': 24081,
 'providing': 48003,
 'greater': 26709,
 'economic': 19963,
 'opportunity': 43158,
 'middle': 38944,
 'class': 12371,
 'families': 22730,
 'during': 19663,
 'regular': 50211,
 'briefing': 9395,
 'speaker': 56688,
 'boehner': 8620,
 'ohio': 42858,
 'questioned': 48660,
 'why': 66076,
 'starting': 57392,
 'session': 54292,
 'adversarial': 3025,
 'note': 42145,
 'too': 61126,
 'harder': 27737,
 'pace': 43995,
 'rising': 51669,
 'costs': 14664,
 'frankly': 24601,
 'weâ': 65856,
 've': 64324,
 'got': 26424,
 'awful': 6203,
 'lot': 36439,
 'unfortunately': 63167,
 'threatening': 60604,
 'bipartisan': 8071,
 'jobs': 32928,
 'essentially': 21512,
 'telling': 59959,
 'what': 65874,
 'our': 43507,
 'commitment': 13265,
 'stand': 57309,
 'up': 63730,
 'we': 65556,
 'break': 9252,
 'brendan': 9315,
 'buck': 9693,
 'spokesman': 56939,
 'ways': 65535,
 'committee': 13272,
 'ryan': 52498,
 'wisc': 66360,
 'noted': 42149,
 '18': 433,
 'voted': 65026,
 'similar': 55354,
 'companion': 13340,
 'sponsored': 56953,
 'susan': 58890,
 'collins': 13019,
 'maine': 37055,
 'ind': 30763,
 'polls': 46500,
 'show': 55004,
 'clear': 12440,
 'majority': 37098,
 'approving': 4913,
 'pipeline': 45880,
 '60': 1576,
 'november': 42214,
 'today': 61008,
 'survey': 58863,
 'saying': 53171,
 'should': 54981,
 'authorize': 6042,
 'project': 47693,
 '25': 937,
 'rest': 51055,
 'unsure': 63632,
 'separate': 54170,
 'polling': 46495,
 'finds': 23534,
 'independents': 30794,
 'moderate': 39655,
 'liberal': 35662,
 'education': 20071,
 'opposed': 43161,
 'along': 3832,
 'overall': 43699,
 'public': 48136,
 'bullish': 9820,
 'job': 32925,
 'creation': 15061,
 'prospects': 47891,
 '10': 115,
 'respondents': 51034,
 'abc': 2163,
 'news': 41532,
 'poll': 46483,
 'significant': 55274,
 'thought': 60576,
 'pose': 46720,
 'risk': 51670,
 'environment': 21149,
 'kasich': 33545,
 'reaffirmed': 49421,
 'call': 10303,
 'forâ': 24446,
 'path': 44682,
 'status': 57477,
 'estimated': 21549,
 'undocumented': 63045,
 'immigrants': 30268,
 'guest': 27078,
 'worker': 66622,
 'program': 47655,
 'meet': 38371,
 'needs': 41257,
 'labor': 34599,
 'market': 37589,
 'cnnâ': 12731,
 'state': 57417,
 'unionâ': 63284,
 'sunday': 58590,
 'morning': 40069,
 'seemed': 53922,
 'disavow': 18053,
 'eliminating': 20403,
 'birthright': 8108,
 'citizenship': 12255,
 'granting': 26619,
 'automatic': 6070,
 'children': 11869,
 'born': 8891,
 'soil': 56294,
 'donâ': 19005,
 'supreme': 58768,
 'court': 14832,
 'gutted': 27227,
 'portion': 46695,
 '2013': 767,
 'fix': 23714,
 'specifying': 56733,
 'states': 57433,
 'localities': 36196,
 'history': 28853,
 'minority': 39246,
 'voter': 65030,
 'suppression': 58757,
 'require': 50842,
 'extra': 22346,
 'scrutiny': 53699,
 'changing': 11499,
 'voting': 65044,
 'laws': 35097,
 'still': 57712,
 'find': 23529,
 'single': 55437,
 'co': 12735,
 'sponsor': 56952,
 'forthcoming': 24412,
 'judged': 33163,
 'completed': 13427,
 'debt': 16297,
 'society': 56236,
 'then': 60366,
 'certainly': 11334,
 'something': 56400,
 'seriously': 54242,
 'considered': 13940,
 'mccain': 38070,
 'ariz': 5151,
 'don': 18940,
 'paid': 44077,
 're': 49373,
 'enter': 21050,
 'question': 48658,
 'ex': 21860,
 'offender': 42768,
 'vote': 65025,
 'federal': 23078,
 'determined': 17464,
 'where': 65906,
 'person': 45306,
 'lives': 36098,
 'some': 56385,
 'permanently': 45228,
 'revoke': 51351,
 'rights': 51583,
 'convicted': 14316,
 'felony': 23180,
 'like': 35825,
 'strip': 58054,
 'felons': 23179,
 'even': 21732,
 'prison': 47458,
 'restore': 51080,
 'after': 3193,
 'served': 54263,
 'sentence': 54146,
 'registering': 50178,
 'burdensome': 9899,
 'myrna': 40766,
 'pã': 48459,
 'rez': 51402,
 'deputy': 17195,
 'democracy': 16898,
 'brennan': 9319,
 'center': 11258,
 'taking': 59428,
 'front': 24845,
 'general': 25569,
 'trajectory': 61473,
 'ease': 19859,
 'restrictions': 51095,
 '1997': 688,
 'reports': 50737,
 '23': 901,
 'expanded': 22115,
 'eligibility': 20397,
 'eased': 19860,
 'restored': 51081,
 'forging': 24334,
 'unusual': 63684,
 'alliances': 3759,
 'capitol': 10587,
 'hill': 28704,
 'rand': 49091,
 'ky': 34559,
 'potential': 46829,
 'leader': 35172,
 'harry': 27834,
 'reid': 50256,
 'nev': 41490,
 'sponsors': 56955,
 'civil': 12271,
 'restoration': 51077,
 '2015': 771,
 'reinstate': 50306,
 'nonviolent': 42024,
 'offenders': 42769,
 'unless': 63353,
 'individual': 30869,
 'term': 60090,
 'probation': 47516,
 'criminal': 15176,
 'biggest': 7909,
 'impediments': 30348,
 'reform': 50066,
 'existing': 22085,
 'give': 25981,
 'low': 36501,
 'feel': 23115,
 'strongly': 58090,
 'continue': 14173,
 'fight': 23417,
 'hopes': 29266,
 'non': 41929,
 'violent': 64787,
 'second': 53822,
 'chance': 11479,
 'doesn': 18826,
 'sentiments': 54159,
 'graham': 26553,
 'example': 21891,
 'radars': 48861,
 'goes': 26254,
 'plan': 46017,
 'incarcerated': 30596,
 'appears': 4797,
 'line': 35920,
 ...}

<h3>Train the naive bayes model</h3>

In [46]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [47]:
X_test

1602    Posted on November 4, 2013 by joandarc | 12 Co...
7023    Today the White House will hold the annual Eas...
3126    \nA grim new Ministry of Defense ( MoD ) repor...
5723    The Bureau of Land Management (BLM) claims to ...
2341    The Kremlin on Friday played down the possibil...
                              ...
2423    19 mins ago 3 Views 0 Comments 0 Likes It's fa...
6212    Home | World | Brexit Lost: Scuppered By May a...
500     The federal government must make regular inter...
4852    Both Donald Trump and Hillary Clinton have str...
2642    (CNN) Sen. John McCain is chastising GOP leade...
Name: text, Length: 1263, dtype: object

<h3>Evaluate Performance</h3>

In [49]:
X_test_tfidf = tfidf.transform(X_test)

In [50]:
X_test_tfidf.toarray()

array([[0.        , 0.02282742, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [51]:
X_test_tfidf.toarray().shape

(1263, 67644)

In [52]:
model.score(X_test_tfidf, y_test)

0.7806809184481394

In [53]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_tfidf)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        FAKE       0.98      0.58      0.73       644
        REAL       0.69      0.99      0.82       619

    accuracy                           0.78      1263
   macro avg       0.84      0.78      0.77      1263
weighted avg       0.84      0.78      0.77      1263

In [54]:
statements = [
            'Google has started providing unlimited cloud storage for its users',
            'Joe Biden is the US president'
]

In [55]:
statements_count = tfidf.transform(statements)
statements_count.toarray().shape

(2, 67644)

In [56]:
statements_count.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [57]:
#statements_count.toarray().shape
model.predict(statements_count)

array(['FAKE', 'REAL'], dtype='<U4')